# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager

  ethernets:
    enp0s3:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.31.112/16
      routes:
        - to: default
          via: 192.168.31.1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4,114.114.114.114,192.168.31.1]
    enp0s10:
      dhcp4: false
      dhcp6: false
      addresses:
        - 172.31.7.112/16
  version: 2
