version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - node.name=es-node1
      - cluster.name=magedu-es-cluster1
      - cluster.initial_master_nodes=es-node1
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - 'es-data:/usr/share/elasticsearch/data'
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    ports:
      - 9200:9200
    restart: always
    networks:
      - elastic
  logstash:
    image: logstash:7.17.7
    container_name: logstash
    volumes:
      - './logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
    ports:
      - 5044:5044
      - 9889:9889
      - 9600:9600
    restart: always
    networks:
      - elastic
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.7
    container_name: kibana
    volumes:
      - './kibana/config:/usr/share/kibana/config'
    ports:
      - 5601:5601
    restart: always
    networks:
      - elastic
    depends_on:
      - elasticsearch
volumes:
  es-data:
    driver: local

networks:
  elastic:
    ipam:
      driver: default
      config:
      - subnet: "10.0.0.0/24"
