apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/opt/data/vol/1"
    server: 172.29.1.1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-wordpress-mysql-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 1Gi
